version: '2'

services:
  webserver:
    build:
       context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/jonathan.carter/Documents/Code/Docker/php-local/src:/var/www/html
      - /Users/jonathan.carter/Documents/Code/Docker/php-local/custom.ini:/usr/local/etc/php/conf.d/custom.ini


    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_runwaytest
